#!/bin/sh
# Run in codespaces after starting
echo "==> Running codespaces post-start script"

# Always want to use ZSH as my default shell (e.g. for SSH)
sudo="sudo"
if [ "${USER}" = "root" ]; then
    sudo=""
fi

if ! grep -q "${USER}.*/bin/zsh" /etc/passwd; then
    $sudo chsh -s /bin/zsh "${USER}"
fi
